name: learn-github-action
run-name: ${{ github.actor }} is learning Github Actions
on: 

  workflow_dispatch:
  

  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

permissions:
  contents: read
  
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          
          - name: Setup node
            uses: actions/setup-node@v3
            with:
                node-version: '14'
                cache: npm
              
          - run: npm install -g bat
          - run: bats -v